sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t pvaz/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pvaz/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-463891942529"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACESS_KEY
    secret_access_key:
        secure: "AWS_SECRET_KEY"       